// src/components/DebugControls.vue
<script setup lang="ts">

import { useEditorStore } from '@/stores/editor';
import { useErrorReportsStore } from '@/stores/error_list';
import { useROSStore } from '@/stores/ros';
import type { ContinueRequest, ContinueResponse } from '@/types/services/Continue';
import type { SetExecutionModeRequest, SetExecutionModeResponse } from '@/types/services/SetExecutionMode';
import type { DebugSettings } from '@/types/types';
import { uuid } from '@/utils';
import { onMounted, onUnmounted, onUpdated, ref } from 'vue';

const debug_check_id = "debug_" + uuid();
const publish_subtrees_id = "publish_subtrees_" + uuid();

const ros_store = useROSStore();
const editor_store = useEditorStore();
const error_store = useErrorReportsStore();

const debugging = ref<boolean>(false);
const publish_subtrees = ref<boolean>(false);

function onNewDebugSettingsMsg(msg: DebugSettings) {
    console.log(msg);
    editor_store.enableDebugging(msg.single_step);
    editor_store.enableSubtreePublishing(msg.publish_subtrees);
}

function onClickStep() {
    if (ros_store.step_service === undefined) {
        error_store.reportError("Step service not available!");
        return;
    }
    ros_store.step_service.callService(
        {} as ContinueRequest,
        (response: ContinueResponse) => {
            if (response.success) {
                console.log("stepped successfully");
            } else {
                error_store.reportError(response.error_message);
            }
        }
    );
}

function handleDebugChange(event: Event) {

    const target = event.target as HTMLInputElement

    if (ros_store.set_execution_mode_service === undefined) {
        error_store.reportError("SetExecutionMode service not available!");
        return;
    }

    const enable = target.checked;
    ros_store.set_execution_mode_service.callService(
        {
            single_step: enable,
            publish_subtrees: publish_subtrees.value,
            collect_performance_data: true,
        } as SetExecutionModeRequest,
        (_response: SetExecutionModeResponse) => {
            console.log("Set execution mode")
        }
    );
    debugging.value = enable;
}

function handlePubSubtreesChange(event: Event) {
    const target = event.target as HTMLInputElement

    if (ros_store.set_execution_mode_service === undefined) {
        error_store.reportError("SetExecutionMode service not available!");
        return;
    }
    const enable = target.checked;

    ros_store.set_execution_mode_service.callService(
        {
            single_step: debugging.value,
            publish_subtrees: enable,
            collect_performance_data: true,
        } as SetExecutionModeRequest,
        (_response: SetExecutionModeResponse) => {

            console.log("Set execution mode")
        }
    );
    publish_subtrees.value = enable;
}

const debug_subscribed = ref<boolean>(false);

ros_store.$onAction((
    {
        name,
        store,
        args,
        after,
        onError
    }
) => {
    if (name !== "changeNamespace") {
        return;
    }

    after((result) => {
        if (ros_store.debug_settings_sub === undefined) {
            debug_subscribed.value = false;
            return;
        } else {
            if (!debug_subscribed.value) {
                console.log("subscribed!")
                ros_store.debug_settings_sub.subscribe(onNewDebugSettingsMsg);
                debug_subscribed.value = true;
            }
        }
    });
})

onMounted(() => {
    if (ros_store.debug_settings_sub === undefined) {
        debug_subscribed.value = false;
        return;
    } else {
        if (!debug_subscribed.value) {
            console.log("subscribed on mount!")
            ros_store.debug_settings_sub.subscribe(onNewDebugSettingsMsg);
            debug_subscribed.value = true;
        }
    }
})

</script>

<template>
    <div class="form-check m-1">
        <input type="checkbox" v-bind:id="debug_check_id" class="form-check-input" v-bind:checked="debugging"
            @change="handleDebugChange" />
        <label class="form-check-label" v-bind:for="debug_check_id">
            Debug
        </label>
    </div>
    <div class="form-check m-1">
        <input type="checkbox" v-bind:id="publish_subtrees_id" class="form-check-input" v-bind:checked="publish_subtrees"
            @change="handlePubSubtreesChange" />
        <label class="form-check-label" v-bind:for="publish_subtrees_id">
            Publish Subtrees
        </label>
    </div>
    <button @click="onClickStep" class="btn btn-primary ms-1" v-if="editor_store.debug">
        <font-awesome-icon icon="fa-solid fa-step-forward" aria-hidden="true" class="show-button-icon" />
        <span class="ms-1 hide-button-text-control">Step</span>
    </button>
</template>

<style lang="scss">
@import "src/assets/utils.scss";
</style>

// src/components/DebugControls.tsx
import React, { ChangeEvent, Component, Fragment } from "react";
import ROSLIB from "roslib";
import { DebugSettings } from "../types/types";
import {
  SetExecutionModeRequest,
  SetExecutionModeResponse,
} from "../types/services/SetExecutionMode";
import { ContinueRequest, ContinueResponse } from "../types/services/Continue";
import { uuid } from "../utils";

interface DebugControlsProps {
  ros: ROSLIB.Ros;
  bt_namespace: string;
  onError: (error_msg: string) => void;
  onPublishingSubtreesChange: (editable: boolean) => void;
}

interface DebugControlsState {
  debugging: boolean;
  publishing_subtrees: boolean;
}

export class DebugControls extends Component<
  DebugControlsProps,
  DebugControlsState
> {
  debug_settings_sub: ROSLIB.Topic<DebugSettings>;
  set_execution_mode_service: ROSLIB.Service<
    SetExecutionModeRequest,
    SetExecutionModeResponse
  >;
  step_service: ROSLIB.Service<ContinueRequest, ContinueResponse>;
  debugCheckID: string;
  publishSubtreesID: string;

  constructor(props: DebugControlsProps) {
    super(props);

    this.state = {
      debugging: false,
      publishing_subtrees: false,
    };

    this.debug_settings_sub = new ROSLIB.Topic({
      ros: props.ros,
      name: props.bt_namespace + "debug/debug_settings",
      messageType: "ros_bt_py_msgs/DebugSettings",
    });

    this.set_execution_mode_service = new ROSLIB.Service({
      ros: props.ros,
      name: props.bt_namespace + "debug/set_execution_mode",
      serviceType: "ros_bt_py_msgs/SetExecutionMode",
    });

    this.step_service = new ROSLIB.Service({
      ros: props.ros,
      name: props.bt_namespace + "debug/continue",
      serviceType: "ros_bt_py_msgs/Continue",
    });

    this.debugCheckID = "debug_" + uuid();
    this.publishSubtreesID = "publish_subtrees_" + uuid();

    this.onNewDebugSettings = this.onNewDebugSettings.bind(this);
    this.onClickStep = this.onClickStep.bind(this);
    this.handleDebugChange = this.handleDebugChange.bind(this);
    this.handlePubSubtreesChange = this.handlePubSubtreesChange.bind(this);
  }

  componentDidMount() {
    this.debug_settings_sub.subscribe(this.onNewDebugSettings);
  }

  componentWillUnmount() {
    this.debug_settings_sub.unsubscribe(this.onNewDebugSettings);
  }

  onNewDebugSettings(msg: any) {
    this.setState({
      debugging: msg.single_step,
      publishing_subtrees: msg.publish_subtrees,
    });
  }

  onClickStep() {
    this.step_service.callService(
      {} as ContinueRequest,
      (response: ContinueResponse) => {
        if (response.success) {
          console.log("stepped successfully");
        } else {
          this.props.onError(response.error_message);
        }
      }
    );
  }

  handleDebugChange(event: ChangeEvent<HTMLInputElement>) {
    const enable = event.target.checked;
    this.set_execution_mode_service.callService(
      {
        single_step: enable,
        publish_subtrees: this.state.publishing_subtrees,
        collect_performance_data: true,
      } as SetExecutionModeRequest,
      function () {
        if (enable) {
          console.log("enabled stepping");
        } else {
          console.log("disabled stepping");
        }
      }.bind(this)
    );
    this.setState({ debugging: enable });
  }

  handlePubSubtreesChange(event: ChangeEvent<HTMLInputElement>) {
    const enable = event.target.checked;
    this.props.onPublishingSubtreesChange(enable);
    this.set_execution_mode_service.callService(
      {
        single_step: this.state.debugging,
        publish_subtrees: enable,
        collect_performance_data: true,
      } as SetExecutionModeRequest,
      function () {
        if (enable) {
          console.log("enabled stepping");
        } else {
          console.log("disabled stepping");
        }
      }.bind(this)
    );
    this.setState({ publishing_subtrees: enable });
  }

  render() {
    let debug_controls = null;
    if (this.state.debugging) {
      debug_controls = (
        <button onClick={this.onClickStep} className="btn btn-primary ms-1">
          <i className="fas fa-step-forward show-button-icon"></i>
          <span className="ms-1 hide-button-text-control">Step</span>
        </button>
      );
    }
    return (
      <Fragment>
        <div className="form-check m-1">
          <input
            type="checkbox"
            id={this.debugCheckID}
            className="form-check-input"
            checked={this.state.debugging}
            onChange={this.handleDebugChange}
          />
          <label className="form-check-label" htmlFor={this.debugCheckID}>
            Debug
          </label>
        </div>
        <div className="form-check m-1">
          <input
            type="checkbox"
            id={this.publishSubtreesID}
            className="form-check-input"
            checked={this.state.publishing_subtrees}
            onChange={this.handlePubSubtreesChange}
          />
          <label className="form-check-label" htmlFor={this.publishSubtreesID}>
            Publish Subtrees
          </label>
        </div>
        {debug_controls}
      </Fragment>
    );
  }
}
