// src/components/NamespaceSelect.vue
/*
 * Copyright 2024 FZI Forschungszentrum Informatik
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * Neither the name of the {copyright_holder} nor the names of its
 *      contributors may be used to endorse or promote products derived from
 *      this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
<script setup lang="ts">
import { ref } from 'vue'
import type {
  ServicesForTypeRequest,
  ServicesForTypeResponse
} from '@/types/services/ServicesForType'
import { notify } from '@kyvg/vue3-notification'
import { useROSStore } from '../stores/ros'
import { useMessasgeStore } from '@/stores/message'
import { usePackageStore } from '@/stores/package'
const ros_store = useROSStore()
const messages_store = useMessasgeStore()
const packages_store = usePackageStore()

let edit_rosbridge_server = ref<boolean>(false)
let new_url = ref<string>(ros_store.url)

function handleNamespaceChange(event: Event) {
  const target = event.target as HTMLSelectElement
  ros_store.changeNamespace(target.value)
}

function updateAvailableNamespaces() {
  if (ros_store.services_for_type_service === undefined) {
    notify({
      title: 'Service not available!',
      text: 'ServiceForType ROS service is not connected!',
      type: 'error'
    })
    return
  }
  ros_store.services_for_type_service.callService(
    // Search for all Tree topics - we expect each BT node to
    // publish one of these, and also offer the corresponding
    // editing and runtime control services.
    {
      type: 'ros_bt_py_interfaces/srv/AddNode'
    } as ServicesForTypeRequest,
    (response: ServicesForTypeResponse) => {
      const namespaces = response.services.map(
        // Chop off the topic name (but not the last slash), which leaves us with the BT
        // namespace
        (x) => x.substr(0, x.lastIndexOf('/')) + '/'
      )
      ros_store.setAvailableNamespaces(namespaces)
      if (ros_store.namespace === '' && namespaces.length > 0) {
        ros_store.changeNamespace(namespaces[0])
      }
    }
  )
}

function editRosbridgeServer() {
  edit_rosbridge_server.value = !edit_rosbridge_server.value
}

function changeRosbridgeServer(event: Event) {
  const target = event.target as HTMLInputElement
  new_url.value = target.value
}

function saveRosbridgeServer() {
  ros_store.setUrl(new_url.value)
  ros_store.connect()
}
</script>

<template>
  <div
    key="connection_status_connected"
    v-if="
      ros_store.connected && packages_store.packages_available && messages_store.messages_available
    "
  >
    <font-awesome-icon
      icon="fa-solid fa-wifi"
      aria-hidden="true"
      class="connected"
      title="Connected"
    />
  </div>
  <div
    key="connection_status_package"
    v-else-if="ros_store.connected && messages_store.messages_available"
  >
    <font-awesome-icon
      icon="fa-solid fa-wifi"
      aria-hidden="true"
      class="packages-missing"
      title="Connected, package list not (yet) available. File browser will not work."
    />
  </div>
  <div key="connection_status_message" v-else-if="ros_store.connected">
    <font-awesome-icon
      icon="fa-solid fa-wifi"
      aria-hidden="true"
      class="messages-missing"
      title="Connected, message info not (yet) available. ROS-type autocompletion will not work."
    />
  </div>
  <div key="connection_status_disconnected" v-else>
    <font-awesome-icon
      icon="fa-solid fa-wifi"
      aria-hidden="true"
      class="disconnected"
      title="Disconnected"
    />
  </div>
  <div class="d-flex flex-row align-items-center">
    <label class="ms-1">Namespace:</label>
    <select
      class="form-select ms-1"
      v-bind:value="ros_store.namespace"
      @change="handleNamespaceChange"
    >
      <option
        v-for="namespace in ros_store.available_namespaces"
        v-bind:key="namespace"
        v-bind:value="namespace"
      >
        {{ namespace }}
      </option>
    </select>
  </div>
  <button type="button" class="btn btn-sm m-1" @click="updateAvailableNamespaces">
    <font-awesome-icon icon="fa-solid fa-sync" aria-hidden="true" />
    <span class="sr-only">Refresh Namespaces</span>
  </button>
  <button type="button" class="btn btn-sm m-1" @click="editRosbridgeServer">
    <font-awesome-icon icon="fa-solid fa-cog" aria-hidden="true" />
    <span class="sr-only">Edit rosbridge server</span>
  </button>
  <div className="d-flex flex-row align-items-center" v-if="edit_rosbridge_server">
    <div class="input-group m-1">
      <label class="input-group-text">Rosbridge Server:</label>
      <input
        class="form-control"
        type="text"
        placeholder="Websocket URL"
        aria-describedby="websocketURL"
        aria-label="Websocket URL"
        v-bind:value="new_url"
        @change="changeRosbridgeServer"
      />
      <button type="button" @click="saveRosbridgeServer" class="btn btn-primary">Save</button>
    </div>
  </div>
</template>

<style>
.connected {
  padding: 0.25rem;
  color: #0caa19;
}

.disconnected {
  padding: 0.25rem;
  color: #ff0000;
}

.packages-missing {
  padding: 0.25rem;
  color: #ff7300;
}

.messages-missing {
  padding: 0.25rem;
  color: #ffd000;
}
</style>

// src/components/NamespaceSelect.tsx
/*
 * Copyright 2024 FZI Forschungszentrum Informatik
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * Neither the name of the {copyright_holder} nor the names of its
 *      contributors may be used to endorse or promote products derived from
 *      this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
import { ChangeEvent, Component } from "react";
import ROSLIB from "roslib";
import {
  ServicesForTypeRequest,
  ServicesForTypeResponse,
} from "../types/services/ServicesForType";
interface NamespaceSelectProps {
  ros: ROSLIB.Ros;
  ros_url: string;
  connected: boolean;
  packages_available: boolean;
  messages_available: boolean;
  currentNamespace: string;
  onNamespaceChange: (namespace: string) => void;
  onError: (error_msg: string) => void;
}

interface NamespaceSelectState {
  available_namespaces: string[];
  edit: boolean;
  ros_uri: string;
}

export class NamespaceSelect extends Component<
  NamespaceSelectProps,
  NamespaceSelectState
> {
  servicesForTypeClient?: ROSLIB.Service<
    ServicesForTypeRequest,
    ServicesForTypeResponse
  >;
  constructor(props: NamespaceSelectProps) {
    super(props);

    this.state = {
      available_namespaces: [],
      edit: false,
      ros_uri: props.ros_url,
    };

    this.updateAvailableNamespaces = this.updateAvailableNamespaces.bind(this);
    this.changeRosbridgeServer = this.changeRosbridgeServer.bind(this);
    this.editRosbridgeServer = this.editRosbridgeServer.bind(this);
    this.saveRosbridgeServer = this.saveRosbridgeServer.bind(this);
    this.handleNamespaceChange = this.handleNamespaceChange.bind(this);
  }

  componentDidMount() {
    this.servicesForTypeClient = new ROSLIB.Service({
      ros: this.props.ros,
      name: "/rosapi/services_for_type",
      serviceType: "rosapi/ServicesForType",
    });

    this.updateAvailableNamespaces();
  }

  updateAvailableNamespaces() {
    this.servicesForTypeClient!.callService(
      // Search for all Tree topics - we expect each BT node to
      // publish one of these, and also offer the corresponding
      // editing and runtime control services.
      {
        type: "ros_bt_py_interfaces/srv/AddNode",
      } as ServicesForTypeRequest,
      (response: ServicesForTypeResponse) => {
        const namespaces = response.services.map(
          // Chop off the topic name (but not the last slash), which leaves us with the BT
          // namespace
          (x) => x.substr(0, x.lastIndexOf("/")) + "/"
        );
        this.setState({
          available_namespaces: namespaces,
        });
        if (this.props.currentNamespace === "" && namespaces.length > 0) {
          this.props.onNamespaceChange(namespaces[0]);
        }
      }
    );
  }

  changeRosbridgeServer(event: ChangeEvent<HTMLInputElement>) {
    this.setState({ ros_uri: event.target.value });
  }

  editRosbridgeServer() {
    if (this.state.edit) {
      this.setState({ edit: false });
    } else {
      console.log("edit rosbridge server");
      this.setState({ edit: true });
    }
  }

  saveRosbridgeServer() {
    console.log("save rosbridge server ");

    this.setState({ edit: false });

    const old_uri = window.location.toString();
    let new_uri = old_uri;
    if (window.location.search.length > 0) {
      new_uri = old_uri.replace(
        window.location.search,
        "?ros_uri=" + this.state.ros_uri
      );
    } else {
      new_uri = old_uri + "?ros_uri=" + this.state.ros_uri;
    }
    if (old_uri != new_uri) {
      window.location.assign(new_uri);
    }
  }

  handleNamespaceChange(event: ChangeEvent<HTMLSelectElement>) {
    this.props.onNamespaceChange(event.target.value);
  }

  render() {
    let edit = null;
    if (this.state.edit) {
      edit = (
        <div className="d-flex flex-row align-items-center">
          <div className="input-group m-1">
            <label className="input-group-text">Rosbridge Server:</label>
            <input
              className="form-control"
              type="text"
              placeholder="Websocket URL"
              aria-describedby="websocketURL"
              aria-label="Websocket URL"
              value={this.state.ros_uri}
              onChange={this.changeRosbridgeServer}
            />
            <button
              type="button"
              onClick={this.saveRosbridgeServer.bind(this)}
              className="btn btn-primary"
            >
              Save
            </button>
          </div>
        </div>
      );
    }

    let connection_state;

    if (this.props.connected) {
      if (this.props.messages_available) {
        if (this.props.packages_available) {
          connection_state = (
            <div key="connection_status_connected">
              <span
                aria-hidden="true"
                title="Connected"
                className="fas fa-wifi connected"
              />
            </div>
          );
        } else {
          connection_state = (
            <div key="connection_status_package">
              <span
                aria-hidden="true"
                title="Connected, package list not (yet) available. File browser will not work."
                className="fas fa-wifi packages-missing"
              />
            </div>
          );
        }
      } else {
        connection_state = (
          <div key="connection_status_message">
            <span
              aria-hidden="true"
              title="Connected, message info not (yet) available. ROS-type autocompletion will not work."
              className="fas fa-wifi messages-missing"
            />
          </div>
        );
      }
    } else {
      connection_state = (
        <div key="connection_status_disconnected">
          <span
            aria-hidden="true"
            title="Disconnected"
            className="fas fa-wifi disconnected"
          />
        </div>
      );
    }

    return (
      <>
        {connection_state}
        <div className="d-flex flex-row align-items-center">
          <label className="ms-1">Namespace:</label>
          <select
            className="form-select ms-1"
            value={this.props.currentNamespace}
            onChange={this.handleNamespaceChange}
          >
            {this.state.available_namespaces.map((x) => (
              <option key={x} value={x}>
                {x}
              </option>
            ))}
          </select>
        </div>
        <button
          type="button"
          className="btn btn-sm m-1"
          onClick={this.updateAvailableNamespaces}
        >
          <span aria-hidden="true" className="fas fa-sync" />
          <span className="sr-only">Refresh Namespaces</span>
        </button>
        <button
          type="button"
          className="btn btn-sm m-1"
          onClick={this.editRosbridgeServer}
        >
          <span aria-hidden="true" className="fas fa-cog" />
          <span className="sr-only">Edit rosbridge server</span>
        </button>
        {edit}
      </>
    );
  }
}
